import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {mkdtempSync,mkdirSync,readFileSync,unlinkSync,copyFileSync} from 'node:fs';import path from 'node:path';import {createApp} from '../app/server.mjs';import {health} from '../app/domain.mjs';
mkdirSync('.qa',{recursive:true});
test('health is readiness, handles Unknown, stale, essential caps and restrictions',()=>{const p={id:'route'},fresh={checks:[true,true,true,true,true],checkedAt:new Date().toISOString(),source:'Manual report'};assert.equal(health({evidence:fresh},p).score,100);assert.equal(health({evidence:{...fresh,checks:[true,true,false,true,true]}},p).score,50);assert.equal(health({evidence:{...fresh,checks:[false,false,false,false,false]}},p).score,1);assert.equal(health({evidence:{...fresh,checks:[true,null,true,true,true]}},p).score,null);assert.equal(health({evidence:{...fresh,checkedAt:'2020-01-01T00:00:00Z'}},p).score,null);assert.equal(health({evidence:{...fresh,restriction:'Suspended'}},p).score,0);assert.equal(health({},null).score,null);});
test('persistent authenticated MVP, permission failures, coordination, encrypted recovery and isolation',async()=>{
 const dir=mkdtempSync(path.resolve('.qa/mvp-'));let app=createApp({dataDir:dir,port:0}),url=await app.listen();
 const password='fixture-passphrase-2026',secret='SYNTHETIC_TEST_TOKEN_NO_REDDIT';
 const call=async(p,b,s=null,options={})=>{const headers={...(b===undefined?{}:{'Content-Type':'application/json',Origin:url}),...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrf}:{}),...options};const r=await fetch(url+'/api/'+p,{method:b===undefined?'GET':'POST',headers,body:b===undefined?undefined:JSON.stringify(b)});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')};};
 const ok=async(p,b,s,status=200)=>{const r=await call(p,b,s);assert.equal(r.status,status,`${p}: ${JSON.stringify(r.body)}`);return r.body;};
 const login=async email=>{const r=await call('login',{email,password});assert.equal(r.status,200);return {cookie:r.cookie.split(';')[0],csrf:r.body.csrf,user:r.body.user};};
 try{
 assert.equal((await call('state')).status,401);assert.equal((await call('setup',{name:'Thomas',email:'owner@example.invalid',password,setupToken:'incorrect'})).status,403);
 await ok('setup',{name:'Thomas',email:'owner@example.invalid',password,setupToken:readFileSync(app.store.setupFile,'utf8')},null,201);assert.equal((await call('setup',{})).status,409);let o=await login('owner@example.invalid');
 assert.equal((await call('clients',{name:'Blocked'},o,{'X-CSRF-Token':'incorrect'})).status,403);assert.equal((await call('clients',{name:'Blocked'},o,{Origin:'https://evil.invalid'})).status,403);
 const badHost=await new Promise((resolve,reject)=>{http.get(url+'/api/state',{headers:{Host:'evil.invalid',Cookie:o.cookie}},r=>{r.resume();resolve(r.statusCode);}).on('error',reject);});assert.equal(badHost,403);
 const c=await ok('clients',{name:'Fixture studio'},o,201),p=await ok('proxies',{name:'Fixture route',endpoint:'http://192.0.2.1:8080'},o,201);
 assert.equal((await call('proxies',{name:'Unsafe secret endpoint',endpoint:'http://user:password@192.0.2.1:8080'},o)).status,400);
 const a=await ok('accounts',{name:'test_asset_01',ownership:true,proxyId:p.id,clientId:c.id},o,201),b=await ok('accounts',{name:'test_asset_02',ownership:true},o,201);assert.equal(a.health.score,null);assert.equal(a.connection,'Not connected');assert.equal((await call('accounts',{name:'TEST_ASSET_01',ownership:true},o)).status,409);
 assert.equal((await call('users',{name:'Member',email:'member@example.invalid',password},o)).status,403);await ok('reauth',{password},o);const member=await ok('users',{name:'Maya',email:'member@example.invalid',password},o,201);let m=await login('member@example.invalid');assert.equal((await ok('state',undefined,m)).accounts.length,0);assert.equal((await call('accounts/'+a.id,undefined,m)).status,404);assert.equal((await call('accounts',{name:'denied_asset',ownership:true},m)).status,403);
 await ok('accounts/'+a.id+'/configure',{proxyId:p.id,clientId:c.id,assignedIds:[member.id]},o);assert.equal((await ok('state',undefined,m)).accounts.length,1);assert.equal((await call('accounts/'+b.id+'/activity',undefined,m)).status,404);assert.equal((await call('accounts/'+a.id+'/archive',{confirm:a.name},m)).status,403);
 assert.equal((await call('accounts/'+a.id+'/claim',{},m)).status,409);await ok('accounts/'+a.id+'/evidence',{checks:[true,true,true,true,true],connection:'Good'},m);assert.equal((await ok('accounts/'+a.id,undefined,m)).health.score,100);
 const claims=await Promise.all([call('accounts/'+a.id+'/claim',{},m),call('accounts/'+a.id+'/claim',{},o)]);assert.deepEqual(claims.map(x=>x.status).sort(),[200,409]);const current=(await ok('accounts/'+a.id,undefined,o)).lease;if(current.userId===m.user.id){assert.equal((await call('accounts/'+a.id+'/release',{},o)).status,409);await ok('accounts/'+a.id+'/release',{confirmInactive:true},o);}else await ok('accounts/'+a.id+'/release',{},o);
 await ok('accounts/'+a.id+'/claim',{},m);await ok('accounts/'+a.id+'/release',{},m);assert.equal((await ok('accounts/'+a.id,undefined,o)).activeDays,1);
 await ok('reauth',{password},o);await ok('accounts/'+a.id+'/secrets',{oauthToken:secret,proxyPassword:'SYNTHETIC_PROXY_SECRET'},o);const projection=await ok('state',undefined,o);assert.equal(JSON.stringify(projection).includes(secret),false);assert.equal((await call('accounts/'+a.id+'/reveal',{field:'oauthToken'},m)).status,403);assert.equal((await ok('accounts/'+a.id+'/reveal',{field:'oauthToken'},o)).value,secret);assert.equal(JSON.stringify(await ok('accounts/'+a.id+'/activity',undefined,o)).includes(secret),false);assert.equal(readFileSync(path.join(dir,'ops.sqlite')).includes(Buffer.from(secret)),false);
 const backup=await ok('backup',{passphrase:password},o);assert.equal(JSON.stringify(backup).includes(secret),false);assert.equal((await call('restore/preview',{backup,passphrase:'incorrect-passphrase'},o)).status,400);assert.equal((await ok('state',undefined,o)).accounts.length,2);
 const corrupt={...backup,data:backup.data.slice(0,-4)+'AAAA'};assert.equal((await call('restore/preview',{backup:corrupt,passphrase:password},o)).status,400);
 const preview=await ok('restore/preview',{backup,passphrase:password},o);assert.equal(preview.accounts,2);assert.equal((await call('restore/confirm',{previewId:preview.previewId,confirm:'wrong'},o)).status,400);assert.equal((await ok('state',undefined,o)).accounts.length,2);
 await ok('accounts/'+a.id+'/configure',{proxyId:null,clientId:c.id,assignedIds:[]},o);const changed=await ok('accounts/'+a.id,undefined,o);assert.equal(changed.health.score,null);assert.equal(changed.lease,null);assert.equal((await call('accounts/'+a.id,undefined,m)).status,404);
 await ok('restore/confirm',{previewId:preview.previewId,confirm:'RESTORE'},o);assert.equal((await call('state',undefined,o)).status,401);o=await login('owner@example.invalid');m=await login('member@example.invalid');const restored=await ok('accounts/'+a.id,undefined,o);assert.equal(restored.paused,true);assert.equal(restored.health.score,null);assert.equal((await ok('accounts/'+a.id+'/reveal',{field:'oauthToken'},await reauthSession(o))).value,secret);assert.equal((await ok('state',undefined,m)).accounts.length,1);
 await ok('accounts/'+b.id+'/archive',{confirm:b.name},o);assert.equal((await ok('state',undefined,o)).accounts.length,1);assert.ok((await ok('accounts/'+b.id+'/activity',undefined,o)).some(e=>e.action==='Account archived'));
 await app.close();app=createApp({dataDir:dir,port:0});url=await app.listen();o=await login('owner@example.invalid');assert.equal((await ok('state',undefined,o)).accounts.length,1);assert.equal((await ok('accounts/'+a.id,undefined,o)).paused,true);
 await ok('reauth',{password},o);await ok('users/'+member.id,{ },o);assert.equal((await call('state',undefined,m)).status,401);assert.equal((await call('login',{email:'member@example.invalid',password})).status,401);
 }finally{await app.close();}
 const original=path.join(dir,'vault.key'),saved=path.join(dir,'vault.key.test-recovery');copyFileSync(original,saved);unlinkSync(original);assert.throws(()=>createApp({dataDir:dir,port:0}),/key missing/);copyFileSync(saved,original);
 async function reauthSession(s){await ok('reauth',{password},s);return s;}
});
