import http from 'node:http';
import { readFileSync,existsSync,unlinkSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isIP } from 'node:net';
import { openStore } from './store.mjs';
import { token,digest,passwordHash,passwordMatches,seal,unseal,backupSeal,backupOpen } from './security.mjs';
import { AppError,requireValue,text,password,redactAccount,health } from './domain.mjs';
import {probeProxy,proxyObservation,publicProxy,PROBE_SOURCE} from './proxy.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
export function createApp({dataDir=path.join(root,'data'),port=4317,publicOrigin=null,proxyProbe=probeProxy,monitorIntervalMs=60000,proxyCooldownMs=10000}={}) {
  if(publicOrigin){const url=new URL(publicOrigin);requireValue(url.protocol==='https:'&&!url.username&&!url.password&&url.pathname==='/'&&!url.search&&!url.hash,'CONFIGURATION','Public origin must be an HTTPS origin without a path.');publicOrigin=url.origin;}
  const store=openStore(dataDir),{db}=store,limits=new Map(),previews=new Map(),streams=new Set();let origin;
  const proxyJobs=new Map(),proxyAttempts=new Map(),staleProxyNotices=new Set();let closing=false;
  const publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,disabled:!!u.disabled});
  const user=id=>db.prepare('SELECT * FROM users WHERE id=?').get(id);
  const owner=u=>requireValue(u.role==='owner','OWNER_ONLY','Only the workspace owner can do this.',403);
  const reauth=s=>requireValue(s.reauth_until>Date.now(),'REAUTH_REQUIRED','Confirm your workspace password before this action.',403);
  const assigned=(u,id)=>u.role==='owner'||!!db.prepare('SELECT 1 FROM assignments WHERE account_id=? AND user_id=?').get(id,u.id);
  const account=(u,id,archived=false)=>{const a=store.get('account',id);requireValue(a&&assigned(u,id)&&(!a.archivedAt||archived&&u.role==='owner'),'NOT_FOUND','Account unavailable or not assigned to you.',404);return a;};
  const emit=()=>{for(const stream of streams)stream.write('event: changed\ndata: {}\n\n');};
  const mutate=(u,id,action,fn,source='Local')=>{const result=store.transaction(()=>{const value=fn();store.audit(u,id,action,'success',source);return value;});emit();return result;};
  const lease=id=>{const l=db.prepare('SELECT l.*,u.name FROM leases l JOIN users u ON u.id=l.user_id WHERE l.account_id=?').get(id);return l?{userId:l.user_id,name:l.name,started:l.started,expires:l.expires,mode:'Manual-only'}:null;};
  const project=a=>({...redactAccount(a,store.get('proxy',a.proxyId),lease(a.id),db.prepare('SELECT COUNT(*) n FROM active_days WHERE account_id=?').get(a.id).n),assignedIds:db.prepare('SELECT user_id FROM assignments WHERE account_id=?').all(a.id).map(r=>r.user_id)});
  const state=u=>{const accounts=store.all('account').filter(a=>!a.archivedAt&&assigned(u,a.id)).map(project),ids=new Set(accounts.map(a=>a.id));return {user:publicUser(u),accounts,proxies:store.all('proxy').filter(p=>u.role==='owner'||accounts.some(a=>a.proxyId===p.id)).map(p=>({...publicProxy(p),checking:proxyJobs.has(p.id)})),clients:store.all('client').filter(c=>u.role==='owner'||accounts.some(a=>a.clientId===c.id)),users:u.role==='owner'?db.prepare('SELECT * FROM users').all().map(publicUser):[],capabilities:{redditLive:'Unavailable',companion:'Unavailable',proxyCheck:'Live diagnostic only'},source:'Local database',time:new Date().toISOString(),notifications:accounts.filter(a=>a.health.score!==100).map(a=>({accountId:a.id,name:a.name,label:a.health.label,reason:a.health.blocked?'Resolve an essential blocker':a.health.stale?'Gather current evidence':'Complete the checklist'})),activity:db.prepare('SELECT * FROM audit ORDER BY id DESC LIMIT 500').all().filter(e=>u.role==='owner'||ids.has(e.account_id)).slice(0,100)};};
  const rate=req=>{const now=Date.now(),ip=req.socket.remoteAddress,old=limits.get(ip),b=old&&old.until>now?old:{n:0,until:now+900000};b.n++;limits.set(ip,b);requireValue(b.n<=12,'RATE_LIMIT','Too many authentication attempts. Try again in 15 minutes.',429);};
  const json=(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value));};
  const cookie=(res,value,seconds=28800)=>res.setHeader('Set-Cookie',`ro_session=${value}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${seconds}${publicOrigin?'; Secure':''}`);
  const body=async req=>{requireValue(req.headers['content-type']?.startsWith('application/json'),'CONTENT_TYPE','Send JSON.',415);let size=0,chunks=[];for await(const c of req){size+=c.length;requireValue(size<=5242880,'TOO_LARGE','Request exceeds 5 MB.',413);chunks.push(c);}try{return JSON.parse(Buffer.concat(chunks).toString());}catch{throw new AppError(400,'INVALID_JSON','Invalid JSON.');}};
  const server=http.createServer(async(req,res)=>{
    res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
    try{
      requireValue(req.headers.host===new URL(origin).host,'HOST_DENIED','Invalid host.',403);
      const p=new URL(req.url,origin).pathname,m=req.method;
      if(!['GET','HEAD'].includes(m))requireValue(req.headers.origin===origin,'ORIGIN_DENIED','Use the application local URL.',403);
      if(!p.startsWith('/api/')){const files={'/':'web/index.html','/app.js':'web/app.js','/operations.js':'web/operations.js','/proxy-ui.js':'web/proxy-ui.js','/app.css':'web/app.css','/font.ttf':'demo/assets/fonts/manrope/Manrope[wght].ttf','/font-license.txt':'demo/assets/fonts/manrope/OFL.txt'},file=files[p];requireValue(m==='GET'&&!!file,'NOT_FOUND','Not found.',404);const mime=file.endsWith('.html')?'text/html':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.ttf')?'font/ttf':'text/plain';res.writeHead(200,{'Content-Type':mime,'Cache-Control':'no-store'});res.end(readFileSync(path.join(root,file)));return;}
      if(p==='/api/bootstrap'&&m==='GET'){json(res,200,{setupRequired:!db.prepare('SELECT COUNT(*) n FROM users').get().n});return;}
      if(p==='/api/setup'&&m==='POST'){
        rate(req);const b=await body(req);requireValue(!db.prepare('SELECT COUNT(*) n FROM users').get().n,'ALREADY_SETUP','Workspace already configured.',409);
        requireValue(existsSync(store.setupFile)&&typeof b.setupToken==='string'&&digest(b.setupToken)===digest(readFileSync(store.setupFile,'utf8').trim()),'SETUP_TOKEN','Use the key in data/setup-token.txt.',403);
        const name=text(b.name,'Name',80),email=emailValue(b.email),hash=await passwordHash(password(b.password)),id=store.id();
        store.transaction(()=>{requireValue(!db.prepare('SELECT COUNT(*) n FROM users').get().n,'ALREADY_SETUP','Workspace already configured.',409);db.prepare('INSERT INTO users(id,name,email,role,password) VALUES(?,?,?,?,?)').run(id,name,email,'owner',hash);store.audit({id,name},null,'Workspace created');});unlinkSync(store.setupFile);json(res,201,{message:'Workspace created. Sign in.'});return;
      }
      if(p==='/api/login'&&m==='POST'){
        rate(req);const b=await body(req),email=typeof b.email==='string'?b.email.toLowerCase().trim():'';requireValue(typeof b.password==='string'&&b.password.length<=128,'LOGIN_FAILED','Email or password incorrect.',401);const u=db.prepare('SELECT * FROM users WHERE email=? AND disabled=0').get(email),dummy='scrypt$'+'0'.repeat(32)+'$'+'0'.repeat(64),matched=await passwordMatches(b.password,u?.password||dummy);requireValue(u&&matched,'LOGIN_FAILED','Email or password incorrect.',401);
        const raw=token(),csrf=token();db.prepare('INSERT INTO sessions(hash,user_id,csrf,expires) VALUES(?,?,?,?)').run(digest(raw),u.id,csrf,Date.now()+28800000);limits.delete(req.socket.remoteAddress);cookie(res,raw);json(res,200,{user:publicUser(u),csrf});return;
      }
      const raw=req.headers.cookie?.split(';').map(c=>c.trim()).find(c=>c.startsWith('ro_session='))?.slice(11),s=raw?db.prepare('SELECT * FROM sessions WHERE hash=? AND expires>?').get(digest(raw),Date.now()):null,u=s&&user(s.user_id);requireValue(u&&!u.disabled,'UNAUTHORIZED','Sign in to continue.',401);if(m!=='GET')requireValue(req.headers['x-csrf-token']===s.csrf,'CSRF_DENIED','Refresh and try again.',403);
      if(p==='/api/me'&&m==='GET'){json(res,200,{user:publicUser(u),csrf:s.csrf});return;}
      if(p==='/api/state'&&m==='GET'){json(res,200,state(u));return;}
      if(p==='/api/logout'&&m==='POST'){db.prepare('DELETE FROM sessions WHERE hash=?').run(s.hash);cookie(res,'',0);json(res,200,{ok:true});return;}
      if(p==='/api/events'&&m==='GET'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-store','Connection':'keep-alive'});res.write('event: connected\ndata: {}\n\n');streams.add(res);const timer=setInterval(()=>{if(!db.prepare('SELECT 1 FROM sessions WHERE hash=? AND expires>?').get(s.hash,Date.now())||user(u.id)?.disabled){res.end();return;}res.write(': keepalive\n\n');},15000);timer.unref();req.on('close',()=>{clearInterval(timer);streams.delete(res);});return;}
      const b=m==='GET'?{}:await body(req);
      if(p==='/api/reauth'&&m==='POST'){rate(req);requireValue(typeof b.password==='string'&&b.password.length<=128&&await passwordMatches(b.password,u.password),'REAUTH_FAILED','Password incorrect.',403);db.prepare('UPDATE sessions SET reauth_until=? WHERE hash=?').run(Date.now()+60000,s.hash);json(res,200,{expires:Date.now()+60000});return;}
      if(p==='/api/users'&&m==='POST'){owner(u);reauth(s);requireValue(db.prepare("SELECT COUNT(*) n FROM users WHERE role='member' AND disabled=0").get().n<5,'TEAM_LIMIT','Maximum five active members.',409);const name=text(b.name,'Name',80),email=emailValue(b.email);requireValue(!db.prepare('SELECT 1 FROM users WHERE email=?').get(email),'DUPLICATE','Email already exists.',409);const hash=await passwordHash(password(b.password)),id=store.id();mutate(u,null,'Member added',()=>{requireValue(db.prepare("SELECT COUNT(*) n FROM users WHERE role='member' AND disabled=0").get().n<5,'TEAM_LIMIT','Maximum five active members.',409);requireValue(!db.prepare('SELECT 1 FROM users WHERE email=?').get(email),'DUPLICATE','Email already exists.',409);db.prepare('INSERT INTO users(id,name,email,role,password) VALUES(?,?,?,?,?)').run(id,name,email,'member',hash);});json(res,201,{id});return;}
      if(p.startsWith('/api/users/')&&m==='POST'){owner(u);reauth(s);const id=p.split('/')[3];requireValue(user(id)?.role==='member','NOT_FOUND','Member not found.',404);mutate(u,null,'Member access revoked',()=>{db.prepare('UPDATE users SET disabled=1 WHERE id=?').run(id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(id);db.prepare('DELETE FROM leases WHERE user_id=?').run(id);});json(res,200,{ok:true});return;}
      if(p==='/api/clients'&&m==='POST'){owner(u);const c={id:store.id(),name:text(b.name,'Client name',80)};mutate(u,null,'Client added',()=>store.put('client',c));json(res,201,c);return;}
      if(p==='/api/proxies'&&m==='POST'){owner(u);if(b.authMode==='password')reauth(s);const proxy=proxyConfiguration(b,store.id());mutate(u,null,'Proxy configured',()=>store.put('proxy',proxy));json(res,201,publicProxy(proxy));return;}
      const proxyEdit=p.match(/^\/api\/proxies\/([^/]+)\/configure$/);
      if(proxyEdit&&m==='POST'){owner(u);const old=store.get('proxy',proxyEdit[1]);requireValue(old,'NOT_FOUND','Proxy not found.',404);if(old.vault||b.authMode==='password')reauth(s);const proxy=proxyConfiguration(b,old.id,old);mutate(u,null,'Proxy configuration updated',()=>{store.put('proxy',proxy);pauseProxyAccounts(proxy.id,u,'Proxy changed · observations invalidated and local account paused',true);});json(res,200,publicProxy(proxy));return;}
      const proxyCheck=p.match(/^\/api\/proxies\/([^/]+)\/check$/);
      if(proxyCheck&&m==='POST'){const proxy=store.get('proxy',proxyCheck[1]);requireValue(proxy&&(u.role==='owner'||store.all('account').some(a=>!a.archivedAt&&a.proxyId===proxy.id&&assigned(u,a.id))),'NOT_FOUND','Proxy unavailable or not assigned to you.',404);requireValue(b.consent===true,'PROBE_CONSENT','Confirm the diagnostic request through this proxy.');json(res,200,await checkProxy(proxy,u));return;}
      if(p==='/api/accounts'&&m==='POST'){owner(u);const name=text(b.name,'Username',22).replace(/^u\//,'');requireValue(/^[a-zA-Z0-9_-]{3,20}$/.test(name),'VALIDATION','Use a valid Reddit username.');requireValue(b.ownership===true,'OWNERSHIP_REQUIRED','Confirm authorization to manage this existing account.');requireValue(!store.all('account').some(a=>a.name.toLowerCase()===name.toLowerCase()),'DUPLICATE_ACCOUNT','Account already exists, including archives.',409);references(b);const a={id:store.id(),name,ownership:true,purpose:typeof b.purpose==='string'?b.purpose.slice(0,300):'',clientId:b.clientId||null,proxyId:b.proxyId||null,mode:'Manual-only',joinedAt:new Date().toISOString(),paused:false,archivedAt:null,evidence:null};mutate(u,a.id,'Account added',()=>store.put('account',a));json(res,201,project(a));return;}
      const match=p.match(/^\/api\/accounts\/([^/]+)(?:\/([^/]+))?$/);
      if(match){const [,id,action]=match,a=account(u,id,action==='activity');
        if(m==='POST'&&action==='open'){throw new AppError(409,'CAPABILITY_UNAVAILABLE','Browser companion is not available yet. No Reddit browser was opened and no verified connection time was recorded.');}
        if(m==='GET'&&!action){json(res,200,project(a));return;}
        if(m==='GET'&&action==='activity'){json(res,200,db.prepare('SELECT * FROM audit WHERE account_id=? ORDER BY id DESC LIMIT 500').all(id));return;}
        if(m==='POST'&&action==='archive'){owner(u);requireValue(b.confirm===a.name,'CONFIRM_REQUIRED','Type the account name to archive.');mutate(u,id,'Account archived',()=>{a.archivedAt=new Date().toISOString();a.paused=true;store.put('account',a);db.prepare('DELETE FROM leases WHERE account_id=?').run(id);});json(res,200,{ok:true});return;}
        if(m==='POST'&&action==='configure'){owner(u);references(b);requireValue(Array.isArray(b.assignedIds)&&b.assignedIds.every(i=>user(i)?.role==='member'&&!user(i).disabled),'VALIDATION','Choose active members.');mutate(u,id,'Account configuration updated',()=>{if(a.proxyId!==(b.proxyId||null)){a.evidence=invalidateEvidence(a.evidence);db.prepare('DELETE FROM leases WHERE account_id=?').run(id);}a.proxyId=b.proxyId||null;a.clientId=b.clientId||null;a.purpose=typeof b.purpose==='string'?b.purpose.slice(0,300):a.purpose;store.put('account',a);db.prepare('DELETE FROM assignments WHERE account_id=?').run(id);for(const uid of new Set(b.assignedIds))db.prepare('INSERT INTO assignments VALUES(?,?)').run(id,uid);const l=lease(id);if(l&&!assigned(user(l.userId),id))db.prepare('DELETE FROM leases WHERE account_id=?').run(id);});json(res,200,{ok:true});return;}
        if(m==='POST'&&action==='evidence'){requireValue(Array.isArray(b.checks)&&b.checks.length===5&&b.checks.every(v=>v===true||v===false||v===null),'VALIDATION','Provide five checklist outcomes.');requireValue(['Unknown','Good','Fail','Not connected'].includes(b.connection),'VALIDATION','Choose a connection observation.');requireValue([null,'Banned','Suspended'].includes(b.restriction||null),'VALIDATION','Choose a restriction type.');if(b.restriction)text(b.reference,'Notice reference',200);if(a.evidence?.restriction&&!b.restriction){owner(u);requireValue(b.clearRestriction===true&&typeof b.reference==='string'&&b.reference.trim().length>0,'RESTRICTION_REVIEW_REQUIRED','A recheck cannot clear a restriction. Owner must record a superseding notice reference.');}requireValue(b.checks[2]!==true||!!store.get('proxy',a.proxyId),'VALIDATION','Configure a required proxy before marking it manually checked.');mutate(u,id,'Manual checklist recorded',()=>{a.evidence={checks:b.checks,connection:b.connection,restriction:b.restriction||null,reference:b.restriction?b.reference.trim():null,cause:b.restriction&&typeof b.cause==='string'&&b.cause.trim()?b.cause.trim().slice(0,300):'Unknown',source:'Manual report',checkedAt:new Date().toISOString(),actor:u.name};if(health(a,store.get('proxy',a.proxyId)).blocked){a.paused=true;db.prepare('DELETE FROM leases WHERE account_id=?').run(id);}store.put('account',a);},'Manual report');json(res,200,project(a));return;}
        if(m==='POST'&&action==='pause'){mutate(u,id,'Account paused',()=>{a.paused=true;store.put('account',a);db.prepare('DELETE FROM leases WHERE account_id=?').run(id);});json(res,200,{ok:true});return;}
        if(m==='POST'&&action==='resume'){const h=health({...a,paused:false},store.get('proxy',a.proxyId));requireValue(!h.blocked&&!h.stale&&h.score!==null,'PREFLIGHT_BLOCKED','Resolve essential failures and record current evidence.',409);mutate(u,id,'Account resumed',()=>{a.paused=false;store.put('account',a);});json(res,200,{ok:true});return;}
        if(m==='POST'&&action==='claim'){const h=health(a,store.get('proxy',a.proxyId));requireValue(!h.blocked&&!h.stale&&h.score!==null,'PREFLIGHT_BLOCKED','Resolve failures, record the checklist and resume first.',409);mutate(u,id,'Manual handoff reserved',()=>{const old=lease(id);requireValue(!old||old.userId===u.id,'SESSION_BUSY',old?`${old.name} holds the account. Request handoff first.`:'Session busy.',409);db.prepare('INSERT INTO leases VALUES(?,?,?,?) ON CONFLICT(account_id) DO UPDATE SET expires=excluded.expires').run(id,u.id,new Date().toISOString(),Date.now()+900000);const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());db.prepare('INSERT OR IGNORE INTO active_days VALUES(?,?)').run(id,day);},'Manual-only');json(res,200,{lease:lease(id),capability:'Manual reservation; browser routing and identity are not enforced.'});return;}
        if(m==='POST'&&action==='release'){const l=lease(id);requireValue(!l||l.userId===u.id||u.role==='owner'&&b.confirmInactive===true,'SESSION_BUSY','Only the holder can release. Owner must confirm inactivity.',409);mutate(u,id,'Reservation released',()=>db.prepare('DELETE FROM leases WHERE account_id=?').run(id));json(res,200,{ok:true});return;}
        if(m==='POST'&&action==='handoff'){requireValue(!!lease(id),'NOT_FOUND','No active reservation.',404);mutate(u,id,'Handoff requested',()=>{});json(res,200,{ok:true});return;}
        if(m==='POST'&&action==='secrets'){owner(u);reauth(s);const value={};for(const field of ['loginEmail','oauthToken','proxyPassword'])if(b[field])value[field]=text(b[field],field,4000);mutate(u,id,'Protected fields saved',()=>{a.vault=seal(value,store.key,id);store.put('account',a);});json(res,200,{ok:true});return;}
        if(m==='POST'&&action==='reveal'){owner(u);reauth(s);requireValue(['loginEmail','oauthToken','proxyPassword'].includes(b.field),'VALIDATION','Select one field.');const value=a.vault?unseal(a.vault,store.key,id)[b.field]||'':'';store.audit(u,id,'Protected field revealed');json(res,200,{value,hideAfterSeconds:20});return;}
      }
      if(p==='/api/backup'&&m==='POST'){owner(u);reauth(s);const payload={schema:1,createdAt:new Date().toISOString(),key:store.key.toString('base64'),users:db.prepare('SELECT * FROM users').all(),records:db.prepare('SELECT * FROM records').all(),assignments:db.prepare('SELECT * FROM assignments').all(),audit:db.prepare('SELECT * FROM audit').all(),days:db.prepare('SELECT * FROM active_days').all()};const backup=await backupSeal(payload,password(b.passphrase));store.audit(u,null,'Encrypted backup exported');json(res,200,backup);return;}
      if(p==='/api/restore/preview'&&m==='POST'){owner(u);reauth(s);let payload;try{payload=await backupOpen(b.backup,password(b.passphrase));}catch{throw new AppError(400,'RESTORE_INVALID','Invalid backup or passphrase.');}validateBackup(payload,u);for(const [id,v]of previews)if(v.expires<Date.now()||v.session===s.hash)previews.delete(id);requireValue(previews.size<5,'RESTORE_BUSY','Try again later.',409);const id=token();previews.set(id,{payload,session:s.hash,expires:Date.now()+300000});json(res,200,{previewId:id,accounts:payload.records.filter(r=>r.kind==='account').length,clients:payload.records.filter(r=>r.kind==='client').length,members:payload.users.filter(r=>r.role==='member').length,warning:'Replaces records. Revokes sessions, invalidates evidence and pauses accounts.'});return;}
      if(p==='/api/restore/confirm'&&m==='POST'){owner(u);reauth(s);const v=previews.get(b.previewId);requireValue(v&&v.session===s.hash&&v.expires>Date.now()&&b.confirm==='RESTORE','RESTORE_INVALID','Preview expired or confirmation missing.');const payload=v.payload;validateBackup(payload,u);mutate(u,null,'Encrypted backup restored',()=>{
        db.exec('DELETE FROM sessions;DELETE FROM leases;DELETE FROM assignments;DELETE FROM active_days;DELETE FROM records;DELETE FROM audit;DELETE FROM users;');
        for(const item of payload.users){const x=item.role==='owner'?{...item,id:u.id,name:u.name,email:u.email,password:u.password,disabled:0}:item;db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').run(x.id,x.name,x.email,x.role,x.password,x.disabled);}
        for(const r of payload.records){const a=JSON.parse(r.data);if(a.vault)a.vault=seal(unseal(a.vault,Buffer.from(payload.key,'base64'),a.id),store.key,a.id);if(r.kind==='account'){a.evidence=null;a.paused=true;}if(r.kind==='proxy'){a.monitorEnabled=false;a.checkedAt=null;a.status='Unknown';a.observedIp=null;a.observedCountry=null;a.revision=store.id();a.source='Restored configuration · unverified';}store.put(r.kind,a);}
        for(const a of payload.assignments)db.prepare('INSERT INTO assignments VALUES(?,?)').run(a.account_id,a.user_id===payload.users.find(x=>x.role==='owner').id?u.id:a.user_id);for(const d of payload.days)db.prepare('INSERT INTO active_days VALUES(?,?)').run(d.account_id,d.day);for(const e of payload.audit)db.prepare('INSERT INTO audit VALUES(?,?,?,?,?,?,?,?)').run(e.id,e.account_id,e.actor_id,e.actor_name,e.action,e.result,e.source,e.time);
      });previews.delete(b.previewId);cookie(res,'',0);for(const stream of streams)stream.end();json(res,200,{message:'Restored. Sign in again; accounts are paused and evidence Unknown.'});return;}
      throw new AppError(404,'NOT_FOUND','Not found.');
    }catch(e){if(res.headersSent){res.end();return;}json(res,e.status||500,{code:e.code||'INTERNAL_ERROR',message:e.status?e.message:'Operation failed. Existing data is preserved. Try again.',retryable:!e.status});}
  });
  function proxyConfiguration(b,id,old=null){const name=text(b.name,'Route name',80),endpoint=text(b.endpoint,'Proxy endpoint',250);let url;try{url=new URL(endpoint);}catch{throw new AppError(400,'VALIDATION','Use http://host:port or socks5://host:port.');}requireValue(['http:','https:','socks5:'].includes(url.protocol)&&url.hostname&&(url.port||/:\d+\/?$/.test(endpoint))&&!url.username&&!url.password&&!url.search&&!url.hash&&(url.pathname==='/'||url.pathname===''),'VALIDATION','Specify host and port without credentials, paths or query parameters.');const expectedIp=b.expectedIp?text(b.expectedIp,'Expected IP',80):null;requireValue(!expectedIp||isIP(expectedIp),'VALIDATION','Enter a valid fixed IPv4 or IPv6 address.');requireValue(!b.targetCountry||b.targetCountry==='US','VALIDATION','This workflow targets the United States.');const authMode=b.authMode||'none';requireValue(['none','password'].includes(authMode),'VALIDATION','Select a supported authentication method.');let vault=null;
    if(authMode==='password'){if(!b.username&&!b.password&&old?.vault)vault=old.vault;else{requireValue(typeof b.username==='string'&&b.username.length>0&&Buffer.byteLength(b.username)<=255&&!/[\r\n:]/.test(b.username)&&typeof b.password==='string'&&b.password.length>0&&Buffer.byteLength(b.password)<=255&&!/[\r\n]/.test(b.password),'VALIDATION','Enter both proxy credentials, up to 255 bytes each.');vault=seal({username:b.username,password:b.password},store.key,id);}}
    requireValue(b.monitorEnabled!==true||b.probeConsent===true,'PROBE_CONSENT','Confirm periodic diagnostic checks before enabling monitoring.');
    return {id,name,endpoint:url.href,provider:b.provider?text(b.provider,'Provider',80):null,targetCountry:'US',targetCity:b.targetCity?text(b.targetCity,'Target city',80):null,expectedIp,authMode,vault,monitorEnabled:b.monitorEnabled===true,probeEnabled:old?.probeEnabled||b.monitorEnabled===true,baselineIp:old?.baselineIp||null,revision:store.id(),status:'Unknown',source:'Local configuration · unverified',checkedAt:null,observedIp:null,observedCountry:null};}
  function pauseProxyAccounts(id,actor,action,invalidate=false){for(const a of store.all('account').filter(a=>!a.archivedAt&&a.proxyId===id)){const changed=!a.paused||!!lease(a.id);if(invalidate)a.evidence=invalidateEvidence(a.evidence);a.paused=true;store.put('account',a);db.prepare('DELETE FROM leases WHERE account_id=?').run(a.id);if(changed||invalidate)store.audit(actor,a.id,action,'blocked',PROBE_SOURCE);}}
  async function checkProxy(proxy,actor){
    requireValue(!closing,'PROXY_BUSY','Application is stopping.',409);requireValue(!proxyJobs.has(proxy.id)&&proxyJobs.size<3,'PROXY_BUSY','A check is already running. Wait and retry.',409);
    requireValue(Date.now()-(proxyAttempts.get(proxy.id)||0)>=proxyCooldownMs,'PROXY_RATE_LIMIT','Wait ten seconds before checking this route again.',429);
    proxyAttempts.set(proxy.id,Date.now());
    const job=(async()=>{let observation;
      try{const credentials=proxy.vault?unseal(proxy.vault,store.key,proxy.id):{};observation=proxyObservation(await proxyProbe(proxy,credentials),proxy);}
      catch(error){observation={status:'Failed',checkedAt:new Date().toISOString(),source:PROBE_SOURCE,observedIp:null,observedCountry:null,latencyMs:null,checkOutcome:'failed',errorCode:error instanceof AppError?error.code:'PROXY_NETWORK',message:error instanceof AppError?error.message:'Proxy check failed. Check provider details and retry.'};}
      const current=store.get('proxy',proxy.id);requireValue(!closing&&current&&current.revision===proxy.revision,'PROXY_CHANGED','Configuration changed during the check. Run a new check.',409);
      const currentActor=user(actor.id);requireValue(currentActor&&!currentActor.disabled&&(currentActor.role==='owner'||store.all('account').some(a=>!a.archivedAt&&a.proxyId===proxy.id&&assigned(currentActor,a.id))),'PROXY_ACCESS_REVOKED','Access changed during the check. Ask the owner to review.',403);
      mutate(actor,null,'Proxy route check · '+proxy.name,()=>{store.put('proxy',{...current,...observation,probeEnabled:true});if(observation.status!=='Available')pauseProxyAccounts(proxy.id,actor,'Proxy check needs attention · local account paused');},PROBE_SOURCE);
      return publicProxy(store.get('proxy',proxy.id));
    })();proxyJobs.set(proxy.id,job);emit();try{return await job;}finally{proxyJobs.delete(proxy.id);if(!closing)emit();}
  }
  const monitor=setInterval(()=>{if(closing||!origin)return;const actor=db.prepare("SELECT * FROM users WHERE role='owner' AND disabled=0").get();if(!actor)return;for(const p of store.all('proxy')){
    const stale=p.probeEnabled&&p.checkedAt&&Date.now()-Date.parse(p.checkedAt)>300000;
    if(stale&&!staleProxyNotices.has(p.id)){staleProxyNotices.add(p.id);store.transaction(()=>pauseProxyAccounts(p.id,actor,'Proxy evidence stale · local account paused'));emit();}else if(!stale)staleProxyNotices.delete(p.id);
    if(p.monitorEnabled&&!proxyJobs.has(p.id)&&Date.now()-(proxyAttempts.get(p.id)||Date.parse(p.checkedAt)||0)>=monitorIntervalMs)checkProxy(p,actor).catch(()=>{});
  }},Math.min(15000,monitorIntervalMs));monitor.unref();
  function invalidateEvidence(e){return e?.restriction?{...e,checks:[true,null,null,null,null],connection:'Unknown'}:null;}
  function emailValue(value){const email=text(value,'Email').toLowerCase();requireValue(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'VALIDATION','Enter a valid email.');return email;}
  function references(b){if(b.clientId)requireValue(!!store.get('client',b.clientId),'VALIDATION','Select an existing client.');if(b.proxyId)requireValue(!!store.get('proxy',b.proxyId),'VALIDATION','Select an existing proxy.');}
  function validateBackup(p,u){
    requireValue(p&&p.schema===1&&typeof p.key==='string'&&Buffer.from(p.key,'base64').length===32&&['users','records','assignments','audit','days'].every(k=>Array.isArray(p[k])),'RESTORE_INVALID','Unsupported backup.');requireValue(p.users.length<=6&&p.records.length<=2000&&p.audit.length<=50000&&p.assignments.length<=10000&&p.days.length<=50000,'RESTORE_INVALID','Backup exceeds limits.');
    const users=new Set(),emails=new Set(),accounts=new Set(),records=new Set();for(const x of p.users){requireValue(typeof x.id==='string'&&typeof x.name==='string'&&typeof x.email==='string'&&['owner','member'].includes(x.role)&&/^scrypt\$[0-9a-f]{32}\$[0-9a-f]{64}$/.test(x.password)&&[0,1].includes(x.disabled)&&!users.has(x.id)&&!emails.has(x.email),'RESTORE_INVALID','Invalid users.');users.add(x.id);emails.add(x.email);}
    const owners=p.users.filter(x=>x.role==='owner');requireValue(owners.length===1&&owners[0].email===u.email&&!p.users.some(x=>x.role==='member'&&x.id===u.id),'RESTORE_INVALID','Backup belongs to another workspace.');
    for(const r of p.records){let a;try{a=JSON.parse(r.data);}catch{throw new AppError(400,'RESTORE_INVALID','Invalid records.');}requireValue(['account','proxy','client'].includes(r.kind)&&typeof r.id==='string'&&r.id===a.id&&typeof a.name==='string'&&!records.has(r.kind+':'+r.id),'RESTORE_INVALID','Invalid records.');records.add(r.kind+':'+r.id);if(r.kind==='account'){accounts.add(r.id);requireValue(/^[a-zA-Z0-9_-]{3,20}$/.test(a.name)&&a.mode==='Manual-only'&&a.ownership===true,'RESTORE_INVALID','Invalid account.');}if(a.vault){try{const fields=unseal(a.vault,Buffer.from(p.key,'base64'),a.id);if(r.kind==='proxy')requireValue(typeof fields.username==='string'&&typeof fields.password==='string','RESTORE_INVALID','Invalid proxy credentials.');}catch{throw new AppError(400,'RESTORE_INVALID','Protected data cannot be recovered.');}}}
    for(const r of p.records)if(r.kind==='account'){const a=JSON.parse(r.data);requireValue((!a.proxyId||records.has('proxy:'+a.proxyId))&&(!a.clientId||records.has('client:'+a.clientId)),'RESTORE_INVALID','Broken references.');}
    for(const a of p.assignments)requireValue(accounts.has(a.account_id)&&users.has(a.user_id),'RESTORE_INVALID','Invalid assignment.');for(const d of p.days)requireValue(accounts.has(d.account_id)&&/^\d{4}-\d{2}-\d{2}$/.test(d.day),'RESTORE_INVALID','Invalid active day.');for(const e of p.audit)requireValue(Number.isSafeInteger(e.id)&&['actor_id','actor_name','action','result','source','time'].every(k=>typeof e[k]==='string'),'RESTORE_INVALID','Invalid audit.');
  }
  server.requestTimeout=30000;server.headersTimeout=15000;
  return {store,server,async listen(){await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve);});const local=`http://127.0.0.1:${server.address().port}`;origin=publicOrigin||local;return local;},async close(){closing=true;clearInterval(monitor);await Promise.allSettled([...proxyJobs.values()]);for(const stream of streams)stream.end();server.closeAllConnections();await new Promise(r=>server.close(r));store.close();}};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const app=createApp({dataDir:process.env.REDDIT_OPS_DATA_DIR||path.join(root,'data'),port:Number(process.env.REDDIT_OPS_PORT||4317),publicOrigin:process.env.REDDIT_OPS_ORIGIN||null});console.log('Reddit Ops local MVP: '+await app.listen());console.log('First setup key: data/setup-token.txt (keep private). No Reddit live integration.');for(const signal of ['SIGINT','SIGTERM'])process.on(signal,async()=>{await app.close();process.exit(0);});}
