import {createRequire} from 'node:module';import {mkdtempSync,mkdirSync,readFileSync} from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createApp} from '../app/server.mjs';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/LE BINH/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
mkdirSync('.qa',{recursive:true});process.env.TEMP=path.resolve('.qa');process.env.TMP=process.env.TEMP;
let browserProxyReady=false;
const dir=mkdtempSync(path.resolve('.qa/browser-')),app=createApp({dataDir:dir,port:0,proxyCooldownMs:0,proxyProbe:async()=>({observedIp:'8.8.8.8',observedCountry:browserProxyReady?'US':'DE',latencyMs:1})}),url=await app.listen(),browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(url))external.push(r.url());});
const password='browser-fixture-passphrase',click=async name=>page.getByRole('button',{name,exact:true}).click(),nav=async name=>page.locator('nav').getByRole('button',{name,exact:true}).click(),submit=async name=>page.locator('dialog').getByRole('button',{name,exact:true}).click();
async function reauth(){await page.locator('dialog').getByLabel('Your password',{exact:true}).fill(password);await submit('Confirm');}
try{
 await page.goto(url);await page.getByLabel('Setup key',{exact:true}).fill(readFileSync(app.store.setupFile,'utf8'));await page.getByLabel('Email',{exact:true}).fill('browser@example.invalid');await page.getByLabel('Password',{exact:true}).fill(password);await click('Create workspace');await page.getByRole('button',{name:'Sign in',exact:true}).waitFor();await page.getByLabel('Email',{exact:true}).fill('browser@example.invalid');await page.getByLabel('Password',{exact:true}).fill(password);await click('Sign in');await page.locator('nav').waitFor();
 await nav('Clients');await click('Add client');await page.locator('dialog').getByLabel('Client name',{exact:true}).fill('Browser studio');await submit('Save');await page.getByRole('heading',{name:'Browser studio',exact:true}).waitFor();
 await nav('Proxy');await click('Add proxy');await page.locator('dialog').getByLabel('Route name',{exact:true}).fill('Browser route');await page.locator('dialog').getByLabel('Server address',{exact:true}).fill('192.0.2.10');await page.locator('dialog').getByLabel('Port',{exact:true}).fill('8080');await submit('Save & continue');await page.locator('[name=checkConsent]').check();await click('Check connection');await page.getByText('Cannot verify connection',{exact:true}).waitFor();await click('Save pending & finish');await click('View proxy routes');await page.getByRole('heading',{name:'Browser route',exact:true}).waitFor();
 await nav('Accounts');await page.locator('.page-heading').getByRole('button',{name:'Add account',exact:true}).click();await page.locator('dialog').getByLabel('Reddit username',{exact:true}).fill('browser_asset');await page.locator('dialog').getByText('Client organization',{exact:true}).click();await page.locator('dialog').getByLabel('Client',{exact:true}).selectOption({label:'Browser studio'});await page.locator('dialog').getByLabel('Required proxy',{exact:true}).selectOption({label:'Browser route · not verified'});await page.locator('dialog input[name="ownership"]').check();await submit('Save & continue');await click('Check connection');await page.getByText('Cannot verify connection',{exact:true}).waitFor();await click('Save pending & finish');await click('View pending account');await click('← Back to Accounts');await page.locator('#account-rows tr[data-id]').waitFor();assert.match(await page.locator('#account-rows').textContent(),/Unknown/);await page.getByRole('button',{name:'More options for browser_asset',exact:true}).click();assert.equal(await page.getByRole('menuitem',{name:'Delete',exact:true}).isEnabled(),true);await page.keyboard.press('Escape');assert.equal(await page.getByRole('menuitem').count(),0);
 await page.reload();await page.locator('#account-rows tr[data-id]').waitFor().catch(async()=>{await nav('Accounts');await page.locator('#account-rows tr[data-id]').waitFor();});await page.locator('#account-rows tr[data-id]').filter({hasText:'u/browser_asset'}).click();await page.getByRole('tab',{name:'Safeguard',exact:true}).click();await click('Record manual checklist');for(let i=0;i<5;i++)await page.locator('dialog select[name="check'+i+'"]').selectOption('pass');await page.locator('dialog select[name="connection"]').selectOption('Good');await submit('Record report');await page.waitForFunction(()=>document.querySelector('.detail-side')?.textContent.includes('50%'));
 browserProxyReady=true;await page.evaluate(async()=>{const {csrf}=await(await fetch('/api/me')).json(),state=await(await fetch('/api/state')).json();const r=await fetch('/api/proxies/'+state.proxies[0].id+'/check',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({consent:true})});if(!r.ok)throw Error('Fixture recheck failed');});await click('Resume');await page.waitForFunction(()=>document.querySelector('.detail-side')?.textContent.includes('100%'));await click('Reserve manual handoff');await page.locator('.session-banner').waitFor();await click('End reservation');await page.getByRole('tab',{name:'Connection & Proxy',exact:true}).click();await click('Set protected details');await reauth();await page.locator('dialog').getByLabel('OAuth token',{exact:true}).fill('SYNTHETIC_BROWSER_TOKEN');await submit('Save');await page.locator('.protected-row').nth(1).getByRole('button',{name:'Show / hide',exact:true}).click();await reauth();await page.waitForFunction(()=>document.getElementById('secret-oauthToken')?.textContent==='SYNTHETIC_BROWSER_TOKEN');await page.waitForFunction(()=>document.getElementById('secret-oauthToken')?.textContent==='••••••••',{},{timeout:25000});
 await nav('Workspace');await click('Add member');await reauth();await page.locator('dialog').getByLabel('Name',{exact:true}).fill('Maya');await page.locator('dialog').getByLabel('Email',{exact:true}).fill('maya-browser@example.invalid');await page.locator('dialog').getByLabel('Initial password',{exact:true}).fill(password);await submit('Create member');await page.getByText('Maya',{exact:true}).waitFor();
 assert.equal(await page.locator('nav').getByRole('button',{name:'Activity',exact:true}).count(),0);assert.equal(await page.locator('nav').getByRole('button',{name:'Settings',exact:true}).count(),0);
 await click('Manage access for browser_asset');await page.locator('dialog').getByLabel('Maya',{exact:true}).check();await submit('Save configuration');await page.locator('.assignment-summary strong').getByText('Maya',{exact:true}).waitFor();
 await page.evaluate(async()=>{const {csrf}=await(await fetch('/api/me')).json(),state=await(await fetch('/api/state')).json();const r=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({name:'owner_only_asset',ownership:true,proxyId:state.proxies[0].id})});if(!r.ok)throw Error('Owner-only fixture failed');});await page.getByRole('button',{name:'Manage access for owner_only_asset',exact:true}).waitFor();
 for(const alias of ['settings','activity']){await page.evaluate(h=>location.hash=h,alias);await page.getByRole('heading',{name:'Workspace',exact:true}).waitFor();assert.equal(await page.locator('nav button.active').textContent(),'Workspace');}await page.reload();await page.getByRole('heading',{name:'Workspace',exact:true}).waitFor();
 await page.locator('.workspace-audit summary').click();assert.match(await page.locator('.workspace-audit').textContent(),/Account configuration updated/);
 await page.setViewportSize({width:1142,height:884});await page.screenshot({path:'.qa/workspace-owner.png',fullPage:true});await page.setViewportSize({width:375,height:884});await page.screenshot({path:'.qa/workspace-mobile.png',fullPage:true});
 await nav('Safeguard');await page.getByRole('heading',{name:'Shared account checklist',exact:true}).waitFor();await page.locator('.policy-review summary').click();assert.match(await page.locator('.policy-review').textContent(),/not automatically verified or scored/);assert.equal(await page.locator('.shared-rule').count(),5);assert.equal(await page.locator('.policy-review a').count(),3);await page.setViewportSize({width:1142,height:884});await page.screenshot({path:'.qa/safeguard-shared.png',fullPage:true});
 for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const width of [375,768,1440]){await page.setViewportSize({width,height:950});for(const name of ['Overview','Accounts','Proxy','Safeguard','Clients','Workspace']){await nav(name);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${theme} ${width} ${name}`);}await nav('Accounts');await page.locator('#account-rows tr[data-id]').filter({hasText:'u/browser_asset'}).click();for(const name of ['Summary','Connection & Proxy','Activities','Safeguard']){await page.getByRole('tab',{name,exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${theme} ${width} ${name}`);}}}
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>document.documentElement.dataset.theme='light');await nav('Overview');await page.evaluate(()=>document.getElementById('toast').hidden=true);await page.screenshot({path:'.qa/mvp-overview.png',fullPage:true});await nav('Accounts');await page.screenshot({path:'.qa/mvp-accounts.png',fullPage:true});await page.locator('#account-rows tr[data-id]').filter({hasText:'u/browser_asset'}).click();await page.screenshot({path:'.qa/mvp-detail.png',fullPage:true});await page.setViewportSize({width:375,height:812});await page.screenshot({path:'.qa/mvp-mobile.png',fullPage:true});
 await click('Sign out');await page.getByLabel('Email',{exact:true}).fill('maya-browser@example.invalid');await page.getByLabel('Password',{exact:true}).fill(password);await click('Sign in');await page.locator('nav').waitFor();await nav('Accounts');assert.equal(await page.locator('#account-rows tr[data-id]').count(),1);assert.equal(await page.getByRole('button',{name:'Add account',exact:true}).count(),0);await page.getByRole('button',{name:'More options for browser_asset',exact:true}).click();assert.equal(await page.getByRole('menuitem',{name:'Delete',exact:true}).isDisabled(),true);await page.keyboard.press('Escape');await page.locator('#account-rows tr[data-id]').filter({hasText:'u/browser_asset'}).click();await page.getByRole('tab',{name:'Connection & Proxy',exact:true}).click();assert.equal(await page.locator('.protected-row').count(),0);assert.match(await page.getByRole('tabpanel').textContent(),/owner only/);
 await nav('Workspace');await page.getByRole('heading',{name:'Your membership',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Add member',exact:true}).count(),0);assert.equal(await page.locator('[data-action="configure"]').count(),0);assert.equal(await page.getByRole('button',{name:'Export backup',exact:true}).count(),0);assert.equal(await page.locator('.workspace-account-row').count(),1);assert.doesNotMatch(await page.locator('#main').textContent(),/owner_only_asset/);assert.equal((await page.locator('.member-table .source').allTextContents()).includes('browser@example.invalid'),false);await page.setViewportSize({width:1142,height:884});await page.screenshot({path:'.qa/workspace-member.png',fullPage:true});
 await click('Sign out');await page.getByLabel('Email',{exact:true}).fill('browser@example.invalid');await page.getByLabel('Password',{exact:true}).fill(password);await click('Sign in');await nav('Workspace');await click('Revoke access for Maya');await reauth();await page.getByText('Revoked',{exact:true}).waitFor();assert.equal(await page.locator('.assignment-summary strong').getByText('Maya',{exact:true}).count(),0);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS: browser setup/login, client/proxy/account CRUD and reload, checklist, manual handoff, encrypted fields and 20s remask, Workspace assignment/revocation/member isolation, hidden Activity/Settings and historical routes, shared policy checklist, six routes/four detail tabs at 375/768/1440 in both themes; no JS errors or external requests.');
}catch(error){console.error('Visible dialog labels:',await page.locator('dialog label').allTextContents());console.error('Dialog open:',await page.locator('dialog').getAttribute('open'));throw error;}finally{await browser.close();await app.close();}
