import {escapeHTML as e,flowStrip} from './operations.js';
const btn=(label,action,id='',primary=false,extra='')=>`<button type="button" class="btn ${primary?'primary':''}" data-action="${action}" ${id?`data-id="${e(id)}"`:''} ${extra}>${label}</button>`;
const time=v=>v?new Date(v).toLocaleString('en-GB',{timeZone:'Asia/Ho_Chi_Minh',dateStyle:'medium',timeStyle:'short'}):'Not checked';
const ready=p=>p.status==='Available'&&(!p.checkedAt||Date.now()-Date.parse(p.checkedAt)<=300000);

export function proxyPage(data,{owner,preview}){
 const passed=data.proxies.filter(ready).length;
 return `<div class="workflow-heading"><div><span class="eyebrow">01 / CONNECTION FOUNDATION</span><h1>Proxy routes</h1><p class="muted">Connect your provider. Check the US exit before assigning an account.</p></div>${owner?btn('Add proxy','add-proxy','',true):''}</div>${flowStrip(preview&&data.accounts.some(a=>a.firstVerifiedAt)?3:passed?2:data.proxies.length?1:0)}
 <div class="ops-summary"><div class="ops-stat"><span>Configured routes</span><strong>${data.proxies.length}</strong></div><div class="ops-stat"><span>${preview?'Mock checks passed':'US route checks passed'}</span><strong>${passed}</strong></div><div class="ops-stat"><span>Target location</span><strong class="country-value">United States</strong></div></div>
 <section class="panel"><div class="panel-head"><div><h2>Your connection routes</h2><p class="subhead">${preview?'Synthetic routes · no network requests':'Backend diagnostics · browser routing unavailable'}</p></div><span class="pill">${preview?'Mock preview':'Local workspace'}</span></div><div class="proxy-card-list">${data.proxies.map(p=>`<article class="route-card"><div class="route-card-title"><div><h3>${e(p.name)}</h3><p>${e(p.provider||'Provider not specified')} · ${e(p.targetCity||'US location requested')}</p></div><span class="pill ${ready(p)?'connected':p.status==='Failed'?'failed':''}">${p.checking?'Checking…':e(p.status)}${preview?' · Mock':''}</span></div>
 <div class="route-facts"><div><span>Configured server</span><strong>${e(p.endpoint)}</strong></div><div><span>Observed exit IP</span><strong>${e(p.observedIp||'Unknown')}</strong></div><div><span>Observed country</span><strong>${e(p.observedCountry||'Unknown')}</strong></div><div><span>Last check</span><strong>${e(time(p.checkedAt))}</strong></div><div><span>Pinned exit IP</span><strong>${e(p.expectedIp||p.baselineIp||'Set on first US pass')}</strong></div><div><span>Monitoring</span><strong>${preview?'Mock':p.monitorEnabled?'Every 60s · while app runs':'Manual checks'}</strong></div></div>
 ${p.message?`<div class="proxy-feedback ${ready(p)?'success':'attention'}"><strong>${e(p.errorCode||p.checkOutcome||'Result')}</strong><p>${e(p.message)}</p></div>`:''}<div class="route-card-footer"><div>${data.accounts.filter(a=>a.proxyId===p.id).map(a=>btn('u/'+e(a.name),'detail',a.id)).join('')||'<span class="small">No account assigned</span>'}<span class="source">${e(p.source)} · ${p.hasCredentials?'Credentials encrypted':'No stored credentials'}</span></div>${btn('Inspect & check','inspect-proxy',p.id,false,p.checking?'disabled':'')}</div></article>`).join('')||`<div class="empty"><h3>Start with your US proxy</h3><p>Copy the fixed-route connection details from your provider.</p>${owner?btn('Set up first proxy','add-proxy','',true):'<p>Ask Thomas to configure a route.</p>'}</div>`}</div></section>
 <p class="ops-note">A diagnostic checks this backend’s route at one point in time. It does not route your Reddit browser, prove office location or guarantee account safety.</p>`;
}

export function wizardHTML(w,{field,select,form,data,preview}){
 const isProxy=w.type==='proxy',p=w.proxy||data.proxies.find(p=>p.id===w.account?.proxyId),draft=w.draft||{};
 const labels=isProxy?['Connection details','Check route','Finish setup']:['Choose proxy & account','Connection checks','Reddit sign-in'];
 const steps=`<ol class="wizard-steps" aria-label="Setup progress">${labels.map((l,i)=>`<li ${i+1===w.step?'aria-current="step"':''}><span>${i+1}</span>${l}</li>`).join('')}</ol><p class="wizard-context">${preview?'Mock · synthetic workflow':isProxy?'Local setup · live backend diagnostic':'Local account · browser companion unavailable'}</p>`;
 if(isProxy&&w.step===1)return steps+form('proxy-setup',
   field('Route name','name','text',draft.name||'','required maxlength="80" placeholder="My US route"')+field('Provider','provider','text',draft.provider||'','maxlength="80" placeholder="Your proxy provider"')+
   `<div class="form-columns">${field('Server address','host','text',draft.host||'','required placeholder="proxy.provider.example"')}${field('Port','port','number',draft.port||'','required min="1" max="65535"')}</div>`+
   select('Protocol','protocol',[['http:','HTTP'],['https:','HTTPS — TLS to proxy'],['socks5:','SOCKS5']],draft.protocol||'http:')+
   `<details class="advanced-fields" ${draft.authMode==='password'?'open':''}><summary>Authentication & fixed IP</summary>${select('Authentication','authMode',[['none','No credentials / provider IP allowlist'],['password','Username & password']],draft.authMode||'none')}
   <div class="form-columns">${field('Proxy username','username','text','','maxlength="255" autocomplete="off" '+(preview?'disabled':''))}${field('Proxy password','proxyPassword','password','','maxlength="255" autocomplete="new-password" '+(preview?'disabled':''))}</div>
   <p class="form-note">${p?.hasCredentials?'Leave both credential fields blank to retain the encrypted credentials. ':'Choose username & password only if your provider requires it. '}Credentials are never returned in account data or logs. Saving them requires your workspace password. HTTP/SOCKS5 proxy authentication is not encrypted to the proxy; use HTTPS if your provider supports it.</p>
   ${field('Expected fixed IP (optional)','expectedIp','text',draft.expectedIp||'','maxlength="80"')}<p class="form-note">Without an expected IP, the first successful US check pins the observed IP. Later changes are blocked until reviewed.</p></details>`+
   field('US city (requested)','targetCity','text',draft.targetCity||'','maxlength="80" placeholder="Optional — not verified by this check"')+
   (!preview?`<label class="check-label"><input name="monitorEnabled" type="checkbox" ${draft.monitorEnabled?'checked':''}>Check this proxy every 60 seconds while Reddit Ops runs.</label><label class="check-label"><input name="probeConsent" type="checkbox">Allow these periodic HTTPS diagnostics through this proxy to Cloudflare. Provider traffic charges may apply.</label>`:'')+
   `<p class="form-note">Target: United States. Saving details alone does not verify a connection. ${p?'Editing pauses assigned local accounts and invalidates connection evidence. Restriction notices and the pinned exit IP are retained.':''}</p>`,'Save & continue');
 if(!isProxy&&w.step===1){const proxies=data.proxies.filter(p=>preview?ready(p):true);if(!proxies.length)return steps+`<div class="empty"><h3>${preview?'Verify a Mock proxy first':'Set up a proxy first'}</h3><p>Configure an assigned route before account setup.</p>${btn('Go to Proxy','wizard-go-proxy','',true)}</div>`;
 return steps+form('account-setup',select('Required proxy','proxyId',proxies.map(p=>[p.id,p.name+(preview?' · Mock passed':ready(p)?' · backend check passed':' · not verified')]),draft.proxyId||proxies[0]?.id)+field('Reddit username','name','text',draft.name||'','required maxlength="20" placeholder="Your existing username"')+field('Purpose','purpose','text',draft.purpose||'','maxlength="300"')+`<details class="advanced-fields"><summary>Client organization</summary>${select('Client','clientId',[['','Independent'],...data.clients.map(c=>[c.id,c.name])],draft.clientId||'')}</details><label class="check-label"><input name="ownership" type="checkbox" required ${draft.ownership?'checked':''}>I own or am authorized to manage this existing account.</label><p class="form-note">${preview?'Synthetic record only. Do not enter real Reddit credentials.':'Save a pending record. Managed Reddit sign-in remains unavailable; a proxy probe cannot enable it.'}</p>`,'Save & continue');}
 if(w.step===2){const result=w.result;const passed=w.ready;
   const checks=isProxy?['Proxy tunnel & HTTPS','US exit country','Pinned exit IP']:['Proxy & fixed US route','Separate account profile','Reddit authorization','Exclusive account session'];
   return steps+`<div class="wizard-route"><strong>${e(p?.name||'Assigned route')}</strong><span>${e(p?.endpoint||'Not configured')}</span></div><div class="preflight-list">${checks.map((label,i)=>{const status=preview?(passed?'Passed · Mock':result?'Needs attention':'Not checked'):!isProxy?'Unavailable':!p?.checkedAt?'Not checked':i===0?(p.observedIp?'Passed':'Failed'):i===1?(p.observedCountry==='US'?'Passed':p.observedCountry?'Failed':'Unknown'):p.checkOutcome==='ip-changed'?'Failed':p.baselineIp||p.expectedIp?(p.observedIp===(p.expectedIp||p.baselineIp)?'Passed':'Unknown'):'Unknown';return `<div><span>${label}</span><span class="pill ${status.startsWith('Passed')?'connected':status==='Failed'?'failed':''}">${status}</span></div>`;}).join('')}</div>
   ${preview&&isProxy?select('Mock check scenario','scenario',[['success','Successful US route'],['failed','Connection failed'],['wrong-country','Wrong country'],['ip-changed','Exit IP changed']],'success'):''}
   ${!preview&&isProxy?'<label class="check-label"><input name="checkConsent" type="checkbox">Send one HTTPS diagnostic to Cloudflare through this proxy. No Reddit request.</label>':''}
   ${result?`<div class="check-result ${passed?'success':'attention'}" role="status"><strong>${passed?(preview?'Mock check passed':'US route check passed'):'Cannot verify connection'}</strong><p>${e(result)}</p>${isProxy?`<p>Observed IP: ${e(p?.observedIp||'Unknown')} · Country: ${e(p?.observedCountry||'Unknown')} · ${e(time(p?.checkedAt))}</p><p class="small">Source: ${e(p?.source||'Not checked')} · Browser routing: Unavailable</p>`:''}</div>`:''}
   <div class="wizard-actions">${isProxy&&data.user.role==='owner'?btn('Edit details','wizard-edit'):''}${btn(passed?'Check again':'Check connection','wizard-check','',true)}${btn(passed?(isProxy?'Continue':'Continue to sign-in'):'Save pending & finish','wizard-next','',false,preview&&!passed?'disabled':'')}</div><p class="form-note">${preview?'Mock checks do not prove a real connection.':isProxy?'12-second timeout. No direct fallback. Country is a diagnostic observation; exact city and browser route remain unverified.':'No managed Reddit browser can be opened yet.'}</p>`;
 }
 if(isProxy)return steps+`<div class="wizard-complete"><span class="pill ${w.ready?'connected':''}">${w.ready?(preview?'Ready · Mock':'Backend route checked'):'Saved · needs verification'}</span><h3>${e(p.name)}</h3><p>${w.ready?(preview?'Assign the synthetic route to a Mock account.':'Route evidence is saved. You can assign this route to an account record; browser connection is the next integration.'):'Your configuration is saved. Inspect the result and retry when ready.'}</p></div><div class="wizard-actions">${btn('View proxy routes','wizard-finish','',true)}${preview&&w.ready?btn('Connect Mock account','wizard-connect-account'):''}</div>`;
 return steps+`<div class="wizard-complete"><span class="pill">${preview?'Mock browser window':'Browser companion unavailable'}</span><h3>u/${e(w.account.name)}</h3><p>${preview?'Simulate signing in to a separate browser. No Reddit access occurs.':'When supported, Ops will open a separate browser through the assigned route. You sign in there yourself.'}</p></div>${!preview?'<div class="check-result attention"><strong>Pending connection</strong><p>No verified account connection recorded. The 24-hour timer has not started.</p></div>':''}<div class="wizard-actions">${preview?btn(w.account.mockIssue?'Continue Mock session':'Confirm Mock sign-in','wizard-sign-in','',true):btn('View pending account','wizard-finish','',true)}</div>`;
}
